# Generated by Django 5.0.2 on 2024-02-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_approved_postapproval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postapproval',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='ApprovedPost',
        ),
        migrations.DeleteModel(
            name='PostApproval',
        ),
    ]
