# Generated by Django 5.0.2 on 2024-02-18 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_approvedpost_postapproval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postapproval',
            name='post',
        ),
        migrations.DeleteModel(
            name='ApprovedPost',
        ),
        migrations.DeleteModel(
            name='PostApproval',
        ),
    ]
