# Generated by Django 5.0.2 on 2024-02-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_postapproval_post_comment_delete_approvedpost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profileimg',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='profile_images'),
        ),
    ]
