# Generated by Django 5.0.2 on 2024-02-19 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_comment_profileimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='profileimg',
        ),
        migrations.AddField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
        ),
    ]
