# Generated by Django 5.0.2 on 2024-02-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_post_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coverimg',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='cover_images'),
        ),
    ]
