# Generated by Django 5.0.2 on 2024-02-21 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
