# Generated by Django 5.0.2 on 2024-02-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_viewedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='budget',
            field=models.TextField(default=''),
        ),
    ]
