# Generated by Django 5.0.2 on 2024-02-22 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_post_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='coverimg',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
    ]
