# Generated by Django 5.0.2 on 2024-02-23 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_followingscount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followingscount',
            old_name='follower',
            new_name='following',
        ),
    ]
